## Loading data using 'read_csv'
 - 미국 시장 재무제표 데이터 크롤링
 https://nbviewer.jupyter.org/gist/FinanceData/35a1b0d5248bc9b09513e53be437ac42

In [1]:
import numpy as np
import pandas as pd

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

pd.set_option('display.float_format', lambda x : '%.3f' % x)
pd.set_option('max_columns', None)

In [3]:
df = pd.read_csv("./materials/my_data/naver_finance/2015_12.csv")

In [11]:
df.head()

,ticker,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
3,BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
4,CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

# 1. Exploratory Data Analysis (EDA)
 - In statistics, exploratory data analysis (EDA) is an approach to analyzing data sets to summarize their main characteristics, often with visual methods
 - 데이터를 처음 받았을 때 그 데이터의 특성을 발견하는 과정
 - Two Parts
   - Meta data: data about data (읽어온 데이터에 대한 정보들) 
       - 데이터 크기
       - 컬럼 명
       - 데이터 타입
       - 비어있는 데이터 
       - etc
   - Univariate descriptive statistics: summary statistics about individual variables (columns)
       - 각각의 column별의 특징들 (컬럼 별 분포, 평균치 이런 것들)
  
## 1.1 Meta Data

In [4]:
df.shape
# 681개의 행, 16개의 열이 있구나

(681, 16)

In [5]:
df.dtypes.value_counts()
# Series 형태로 알려줌! 이런거 알고 있는게 중요함. 
# float64 형태의 컬럼이 15개, object 형태의 컬럼이 1개 있음.

float64    15
object      1
dtype: int64

In [6]:
df.info()
# df에 대한 정보가 나옴.
# 각각의 컬럼에 대해서 mapping되어있는 것을 보여줌. 
# ticker의 경우 681개의 데이터가 모두 null이 아님을 알려줌 (어느정도 비어있는지, 어떤 dtype인지)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Data columns (total 16 columns):
ticker       681 non-null object
매출액(억원)      680 non-null float64
영업이익률(%)     680 non-null float64
순이익률(%)      680 non-null float64
당기순이익(억원)    680 non-null float64
ROE(%)       665 non-null float64
ROA(%)       665 non-null float64
ROIC(%)      611 non-null float64
EPS(원)       681 non-null float64
BPS(원)       681 non-null float64
SPS(원)       681 non-null float64
PER(배)       668 non-null float64
PBR(배)       681 non-null float64
PSR(배)       668 non-null float64
price        681 non-null float64
price2       681 non-null float64
dtypes: float64(15), object(1)
memory usage: 85.2+ KB

In [7]:
df['ticker'].dtype

dtype('O')

 - Rename Columns

In [8]:
# 컬럼명 수정
df = df.rename(columns = {"ticker" : "종목명"})
df.head()

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
3,BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
4,CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

## 1.2 `describe()`

In [9]:
df.describe()
# column은 그대론데, 각각의 column에 해당하는 값들의 기본적인 통계량을 알려줌
# count: 몇개 있는지.

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
count,680.000,680.000,680.000,680.000,665.000,665.000,611.000,681.000,681.000,681.000,668.000,681.000,668.000,681.000,681.000
mean,30112.802,3.882,7.669,1312.761,4.512,1.837,-3.009,426.081,47451.880,95471.752,18.921,1.582,1.922,47344.200,41784.562
std,108134.170,13.143,151.567,10133.596,130.083,9.512,195.156,34193.002,152959.285,316794.457,134.916,2.040,19.849,117063.700,96318.573
min,3.561,-191.601,-193.426,-22092.438,-529.306,-136.813,-4685.987,-844700.060,-230961.190,50.177,-1435.921,-2.829,0.011,158.000,154.000
25%,1727.089,1.532,0.369,10.859,0.828,0.275,1.357,22.964,4110.551,7504.220,4.674,0.622,0.310,3903.000,4060.000
50%,4692.060,4.194,3.067,118.918,5.350,2.305,5.208,539.109,10988.989,22559.920,11.743,0.957,0.590,12018.000,10900.000
75%,15243.673,8.314,6.612,504.201,9.766,5.338,10.550,2197.652,39550.230,72356.336,24.062,1.672,1.142,40496.000,39750.000
max,2006534.900,64.273,3923.338,190601.440,3122.573,60.287,271.957,93713.010,3017474.000,5553036.500,2808.262,21.154,511.718,1225000.000,1064000.000

In [10]:
# Transpose >> DataFrame의 x축과 y축을 변경함
df.describe().T

,count,mean,std,min,25%,50%,75%,max
매출액(억원),680.000,30112.802,108134.170,3.561,1727.089,4692.060,15243.673,2006534.900
영업이익률(%),680.000,3.882,13.143,-191.601,1.532,4.194,8.314,64.273
순이익률(%),680.000,7.669,151.567,-193.426,0.369,3.067,6.612,3923.338
당기순이익(억원),680.000,1312.761,10133.596,-22092.438,10.859,118.918,504.201,190601.440
ROE(%),665.000,4.512,130.083,-529.306,0.828,5.350,9.766,3122.573
ROA(%),665.000,1.837,9.512,-136.813,0.275,2.305,5.338,60.287
ROIC(%),611.000,-3.009,195.156,-4685.987,1.357,5.208,10.550,271.957
EPS(원),681.000,426.081,34193.002,-844700.060,22.964,539.109,2197.652,93713.010
BPS(원),681.000,47451.880,152959.285,-230961.190,4110.551,10988.989,39550.230,3017474.000
SPS(원),681.000,95471.752,316794.457,50.177,7504.220,22559.920,72356.336,5553036.500
PER(배),668.000,18.921,134.916,-1435.921,4.674,11.743,24.062,2808.262
PBR(배),681.000,1.582,2.040,-2.829,0.622,0.957,1.672,21.154
PSR(배),668.000,1.922,19.849,0.011,0.310,0.590,1.142,511.718
price,681.000,47344.200,117063.700,158.000,3903.000,12018.000,40496.000,1225000.000
price2,681.000,41784.562,96318.573,154.000,4060.000,10900.000,39750.000,1064000.000

In [11]:
# 1. numerical 
# describe의 argument 중 include 
# >> 어떤 것만 포함할 지 결정할 수 있음
# np.number >> 숫자형에 해당하는 것만 describe() >> 사실 default랑 똑같음
df.describe(include = [np.number]).T.head() # = df.describe()

,count,mean,std,min,25%,50%,75%,max
매출액(억원),680.000,30112.802,108134.170,3.561,1727.089,4692.060,15243.673,2006534.900
영업이익률(%),680.000,3.882,13.143,-191.601,1.532,4.194,8.314,64.273
순이익률(%),680.000,7.669,151.567,-193.426,0.369,3.067,6.612,3923.338
당기순이익(억원),680.000,1312.761,10133.596,-22092.438,10.859,118.918,504.201,190601.440
ROE(%),665.000,4.512,130.083,-529.306,0.828,5.350,9.766,3122.573

In [12]:
# dtype을 나타낼 때, string으로 해도 되고, library의 datatype 자체로 해도 됨

In [13]:
df.describe(percentiles = [0.01, 0.03, 0.99]).T.head(2)
# 4분위선의 percentage를 조정해 줄 수 있음
# 50% 는 median으로서 기본적으로 박혀있음. (변경 불가)

,count,mean,std,min,1%,3%,50%,99%,max
매출액(억원),680.000,30112.802,108134.170,3.561,90.991,260.989,4692.060,467457.632,2006534.900
영업이익률(%),680.000,3.882,13.143,-191.601,-24.020,-16.146,4.194,28.584,64.273

In [22]:
# 2. categorical data일 경우
df.describe(include = [np.object, pd.Categorical]).T.head()
# unique = 종목명들 중 중복되지 않는 것들
# top = 얼마나 자주 나왔냐 >> 여기서는 사실상 의미 없음 모든 데이터의 빈도수가 1이므로

    count unique         top freq
종목명   681    681  한화갤러리아타임월드    1

 - exclude >> include랑 반대로 빼줄수도 있음

In [23]:
df.describe(exclude = [np.number]).T.head(2)

    count unique         top freq
종목명   681    681  한화갤러리아타임월드    1

 - 참고: `quantile()` method
     - 백분위수 구하기

In [14]:
df['PER(배)'].quantile(.2)
# 하위 20% 분위에 있는 data를 가져옴 (default는 q = 0.5)
df['PER(배)'].quantile([.1, .2, .3])
# 반환값이 많으면 series로 반환
# 이렇게 series로 묶어서 주면, 10%, 20%, 30%에 해당하는 data를 가져옴

-1.630518

0.100   -10.562
0.200    -1.631
0.300     6.177
Name: PER(배), dtype: float64

## 1.3 `unique(), value_counts()`

In [17]:
# For DataFrame => nunique() 만 사용
# unique() >> 유일한 data들을 series로 반환해줌
# nunique() >> 유일한 data들이 몇개 있는지 return해줌 >> 빈칸은 count하지 않음
df.nunique()

종목명          681
매출액(억원)      680
영업이익률(%)     667
순이익률(%)      672
당기순이익(억원)    680
ROE(%)       655
ROA(%)       650
ROIC(%)      610
EPS(원)       681
BPS(원)       681
SPS(원)       681
PER(배)       668
PBR(배)       680
PSR(배)       668
price        628
price2       620
dtype: int64

In [ ]:
# for series => unique(), nunique(), value_counts()
df['종목명'].unique()
# unique >> 유일한 값들을 series로 뱉어줌

In [27]:
df['종목명'].nunique()

681

In [22]:
df['종목명'].value_counts()
# 각 값들이 몇개의 중복된 값을 가지고 있는지 알려줌

성안          1
휴켐스         1
롯데푸드        1
세방          1
서흥          1
           ..
현대종합상사      1
웰바이오텍       1
계양전기        1
동아쏘시오홀딩스    1
국도화학        1
Name: 종목명, Length: 681, dtype: int64

In [23]:
# value_counts() 는 nan값을 세지 않는다!
b = pd.DataFrame({'a': [np.nan, 1, 2]})['a']
# DF로 만든 후 'a'의 컬럼을 indexing 했기 때문에 Series로 return해준다,

In [30]:
b.value_counts()
# value_counts()는 nan의 개수를 세어주지 않음 >> 이거 했는데 nan이 없다고 해서 없는줄 알면x

2.000    1
1.000    1
Name: a, dtype: int64

 - Example

In [24]:
a = pd.read_csv('./materials/my_data/symbol_sector.csv', index_col = 0)
# index_col = 0 >>  0번쨰 column을 index 컬럼으로 지정하겠다 이말임. 
# 지금은 column명이 없기 때문에 그냥 숫자로 indexing

In [25]:
a.head()

                 Sector
AJ네트웍스  산업용 기계 및 장비 임대업
AJ렌터카          운송장비 임대업
AK홀딩스            기타 금융업
AP우주통신         전자부품 제조업
BGF              종합 소매업

In [26]:
a.shape
a['Sector'].nunique()
# 1142개의 ticker들 중에 sector의 종류가 129개가 있음을 알 수 있음

(1142, 1)

129

In [27]:
a['Sector'].value_counts()
# 각각의 values가 몇개 있는지 count

기타 금융업              110
자동차 신품 부품 제조업        46
의약품 제조업              44
전자부품 제조업             38
1차 철강 제조업            38
                   ...
기타 상품 전문 소매업          1
동물성 및 식물성 유지 제조업      1
스포츠 서비스업              1
사진장비 및 광학기기 제조업       1
산업용 기계 및 장비 임대업       1
Name: Sector, Length: 129, dtype: int64

## 1.4 정렬
### 1.4.1 top n

In [35]:
# 특정 column을 기준으로 데이터를 정렬함

In [30]:
# PER(배) column의 값이 가장 작은 top 5개를 보여줘
df.nsmallest(5, "PER(배)")

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
587,한국콜마홀딩스,2995.671,15.055,0.348,10.437,-0.359,0.238,2.137,-45.267,12915.290,18266.559,-1435.921,5.033,3.558,65000.000,33700.000
370,쌍방울,1426.374,0.725,-0.362,-5.169,-0.408,-0.290,-4.081,-5.266,1370.153,1453.103,-415.912,1.598,1.507,2190.000,2040.000
652,현대엘리베이터,14486.539,10.804,-0.348,-50.366,-0.800,-0.354,6.630,-179.554,26043.530,64214.344,-335.275,2.312,0.937,60200.000,57400.000
576,한국수출포장공업,2306.794,1.168,-0.104,-2.400,-0.106,-0.081,0.226,-60.010,56474.867,57669.840,-332.445,0.353,0.346,19950.000,17900.000
262,보락,310.667,4.119,-0.555,-1.725,-0.425,-0.341,6.625,-2.879,667.945,518.643,-271.617,1.171,1.508,782.000,1156.000

In [31]:
# 1) 전체 데이터에서 PER이 가장 작은 100개를 가져오고,
# 2) 그 중에서 당기순이익이 가장 큰 5개를 보여줘
df.nsmallest(100, "PER(배)").nlargest(5, '당기순이익(억원)')

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
634,한화,413762.880,1.833,0.291,1205.150,-6.696,0.090,3.775,-3778.015,59727.324,548480.500,-10.145,0.642,0.070,38327.000,35050.000
587,한국콜마홀딩스,2995.671,15.055,0.348,10.437,-0.359,0.238,2.137,-45.267,12915.290,18266.559,-1435.921,5.033,3.558,65000.000,33700.000
246,무림페이퍼,11567.717,6.260,0.007,0.786,-1.179,0.004,0.396,-106.895,9207.081,27800.790,-28.486,0.331,0.110,3045.000,2650.000
262,보락,310.667,4.119,-0.555,-1.725,-0.425,-0.341,6.625,-2.879,667.945,518.643,-271.617,1.171,1.508,782.000,1156.000
170,대유플러스,4957.816,0.294,-0.035,-1.729,-8.364,-0.023,1.226,-90.072,1040.880,5626.177,-13.212,1.143,0.212,1190.000,945.000

### 1.4.2 Sort

In [38]:
df.sort_values("EPS(원)").head()
# EPS가 낮은 것부터 오름차순 (ascending)으로 정렬
# default가 ascending

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
280,삼부토건,4467.503,-16.259,-141.681,-6329.583,-460.176,-31.622,-68.083,-844700.060,-230961.190,608502.560,-0.049,-0.180,0.068,20825.000,1058.000
162,대우조선해양,154436.110,-13.756,-14.305,-22092.438,-132.523,-12.067,-33.604,-139077.800,43577.367,1024004.800,-0.365,1.163,0.050,25350.000,22400.000
193,동부제철,23207.922,3.386,-2.071,-480.683,-174.038,-1.530,3.399,-110540.030,3673.298,5553036.500,-0.569,17.127,0.011,101747.000,48500.000
129,남광토건,3023.887,-16.840,-25.474,-770.301,578.247,-20.144,nan,-49479.120,4025.999,194234.720,-0.438,5.378,0.111,14999.000,7280.000
103,고려개발,6070.612,-13.137,-19.734,-1197.971,3122.573,-17.058,-89.292,-29165.465,-15729.051,147793.380,nan,-1.203,nan,18694.000,12430.000

In [39]:
df.sort_values("EPS(원)", ascending = False).head()
# descending, EPS가 큰 것부터 내림차순으로 정렬하고 싶을 경우

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
74,SK,392995.250,3.580,14.120,55492.590,70.565,10.887,5.491,93713.010,222855.360,688906.060,2.566,1.079,0.349,240500.000,229500.000
410,영풍,26153.832,-0.211,3.439,899.401,5.127,2.282,-0.611,69988.860,1500147.500,1419829.800,15.674,0.731,0.773,1097000.000,1064000.000
537,태광산업,28043.580,5.698,3.730,1046.142,2.988,2.716,5.303,67395.090,3017474.000,2518733.500,16.173,0.361,0.433,1090000.000,947000.000
355,신세계,25639.852,10.224,16.895,4331.819,14.262,5.466,2.239,40842.977,307358.160,260430.470,5.631,0.748,0.883,230000.000,176000.000
461,일성신약,617.451,4.194,160.100,988.539,30.556,26.524,-11.557,37163.133,236902.940,23212.450,3.081,0.483,4.933,114500.000,123000.000

In [32]:
# 2개 이상의 기준으로 정렬할 때 >> 기준을 list로 전달하고, 오름 내림도 순서에 맞춰서 전달
# 1) 먼저 순이익률(%)을 기준으로 작은 것 부터 정렬한 후 
# 2) 순이익률이 동일하게 같을 경우, 그 것들은 EPS를 내림차순으로 정렬해라
df.sort_values(['순이익률(%)', 'EPS(원)'], ascending = [True, False]).head()

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
473,제이준코스메틱,80.113,-134.063,-193.426,-154.958,nan,nan,nan,-1901.424,1599.755,983.025,-3.245,3.857,6.277,9255.000,15957.000
534,키위미디어그룹,56.776,-58.565,-172.041,-97.678,-24.583,-13.778,-18.081,-122.804,487.672,71.381,-7.304,1.839,12.566,897.000,1090.000
454,인스코비,163.134,-29.122,-150.446,-245.428,-100.358,-67.654,-16.512,-353.219,343.969,245.169,-4.459,4.579,6.424,1575.000,1705.000
280,삼부토건,4467.503,-16.259,-141.681,-6329.583,-460.176,-31.622,-68.083,-844700.060,-230961.190,608502.560,-0.049,-0.180,0.068,20825.000,1058.000
226,롯데관광개발,446.681,3.444,-111.703,-498.959,-36.074,-25.309,1.325,-1171.188,3257.066,1047.084,-6.567,2.362,7.346,7691.000,6660.000

## 1.5 Setting Subset 
### 1.5.1 By columns
 - 컬럼의 이름을 가지고 subset 추출하기

In [33]:
df['EPS(원)']
# column을 하나만 선택하면 DF가 아닌 Series의 type로 반환함.

0     -3245.741
1      3071.872
2      1853.180
3     15693.808
4      5780.626
         ...
676     607.136
677     100.195
678     896.118
679     301.592
680     227.189
Name: EPS(원), Length: 681, dtype: float64

In [37]:
df[ ['EPS(원)', '종목명'] ].head()
# column을 2개 이상 선택하려고 하면 Series로는 어려움
# >> df안에 list형태로 전달해야함 
# >> bracket이 2중으로 쌓이게 된다 -> 하나는 DataFrame용, 하나는 안의 전달하는 list용

     EPS(원)      종목명
0 -3245.741    AK홀딩스
1  3071.872      BGF
2  1853.180  BNK금융지주
3 15693.808      BYC
4  5780.626       CJ

In [36]:
# column은 하나지만, series형태가 아니라 DataFrame형태롤 return 받고 싶다면
# 하나의 column을 list형태로 넣어주면 된다. 
df[ ['EPS(원)'] ].head()

     EPS(원)
0 -3245.741
1  3071.872
2  1853.180
3 15693.808
4  5780.626

In [38]:
type(df['순이익률(%)'])  # 대괄호 안씌우면 series
type(df[['순이익률(%)', '당기순이익(억원)']]) # 대괄호 씌우면 DataFrame

pandas.core.series.Series

pandas.core.frame.DataFrame

In [39]:
df[ ['ROE(%)', 'ROA(%)', 'ROIC(%)'] ].head()
# 이렇게, column명에 RO가 앞에 붙은 놈들을 manually말고 쉽게 가져오고 싶다면?
# 컬럼이 엄청 많으면 어렵겠지?

   ROE(%)  ROA(%)  ROIC(%)
0  -7.677  -1.421   15.120
1  22.771  10.327  271.957
2   9.116   0.609      nan
3   3.546   2.024   13.235
4   5.874   2.365    5.821

 - `filter()`

In [40]:
# RO like한, RO같은, RO가 들어간 컬럼만 가져오고 싶다 >> use filter()
df.filter(like = "RO").head()

   ROE(%)  ROA(%)  ROIC(%)
0  -7.677  -1.421   15.120
1  22.771  10.327  271.957
2   9.116   0.609      nan
3   3.546   2.024   13.235
4   5.874   2.365    5.821

In [47]:
# 나는 percentage와 관련한 지표만 보고 싶다
df.filter(like = '(%)').head()

   영업이익률(%)  순이익률(%)  ROE(%)  ROA(%)  ROIC(%)
0     3.787   -1.334  -7.677  -1.421   15.120
1     4.236    3.526  22.771  10.327  271.957
2    13.455   10.253   9.116   0.609      nan
3    11.598    7.222   3.546   2.024   13.235
4     5.789    2.604   5.874   2.365    5.821

In [48]:
# regex: regular expression
# 특정 문자열을 특정한 format으로 가져오는 역할을 함
# 점프 투 파이썬에서 정규 표현식에 대해서 더 잘 알아볼 수 있음

# P로 시작하고 R로 끝나는 컬럼들만 보고 싶을 경우
df.filter(regex = "P\w+R").head()

   PER(배)  PBR(배)  PSR(배)
0 -19.472   1.453   0.298
1  28.779   5.665   1.007
2   4.544   0.389   0.426
3  29.279   1.014   2.118
4  40.944   2.146   0.398

### 1.5.2 Setting Subsets By dtype
 - 데이터 타입을 가지고 subset 추출하기

In [42]:
# 각 컬럼이 가지고 있는 dtype의 개수를 세줌
df.get_dtype_counts()

C:\Users\bluke\anaconda3\envs\py37_32\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: `get_dtype_counts` has been deprecated and will be removed in a future version. For DataFrames use `.dtypes.value_counts()

float64    15
object      1
dtype: int64

In [50]:
# float형을 가진 column들만 선택하기 
df.select_dtypes(include = ['float']).head()

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
3,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
4,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

In [43]:
df.select_dtypes(include = ['object']).head()
# string이나 str로 넣으면 (x)
# 무조건 object로 넣어야 한다.

       종목명
0    AK홀딩스
1      BGF
2  BNK금융지주
3      BYC
4       CJ

### 1.5.3 By rows
 - 행(가로)을 기준으로 subset을 추출하는 방법 (아까까지는 column, 열을 기준으로 가져옴)

In [52]:
df.head()

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
3,BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
4,CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

In [44]:
nameDF = df.set_index("종목명")
nameDF.head()

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

#### 1.5.3.1 iloc, loc

In [54]:
# iloc >> integer로 indexing을 하는 loc >> i + loc으로 생각하면 됨

In [55]:
# nameDF[0]  >> column명이 0 (integer)인 column을 Series로 가져와라
# 당연히 지금은 error가 남 >> column명에 0이 없으므로

In [56]:
# row의 index대로 따오려면, iloc을 붙여줘야 가능하다 
# 0번째 row를 가져와라 (가로의 key - value 형태의 dictionary를 가져와서 Series로 가져옴)
nameDF.iloc[0].head()

매출액(억원)     28071.479
영업이익률(%)        3.787
순이익률(%)        -1.334
당기순이익(억원)    -374.431
ROE(%)         -7.677
Name: AK홀딩스, dtype: float64

In [45]:
# row를 2개 이상 가져오고 싶을 경우 >> list로 전달해주면 됨
# 이번에는 DataFrame으로 가져오고, 세로가 아닌 가로로 DF format그대로 가져옴
nameDF.iloc[ [0, 1] ].head()

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000

In [58]:
# loc >> integer가 아니라 index의 이름 자체를 가지고  row를 가져올 때
nameDF.loc[ ['삼성전자', 'CJ']]

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
삼성전자,2006534.900,13.164,9.499,190601.440,11.159,8.066,15.904,2197.652,23714.760,23587.871,11.467,1.063,1.069,25200.000,36040.000
CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

In [59]:
# 역시나 series가 아니라 string으로 전달하면 Series를 가져옴 (세로로)
nameDF.loc['삼성전자']

매출액(억원)     2006534.900
영업이익률(%)         13.164
순이익률(%)           9.499
당기순이익(억원)    190601.440
ROE(%)           11.159
ROA(%)            8.066
ROIC(%)          15.904
EPS(원)         2197.652
BPS(원)        23714.760
SPS(원)        23587.871
PER(배)           11.467
PBR(배)            1.063
PSR(배)            1.069
price         25200.000
price2        36040.000
Name: 삼성전자, dtype: float64

#### 1.5.3.2 Select rows by prefix

In [49]:
# 반드시 index를 sort해야만 사용할 수 있음 
nameDF = nameDF.sort_index()
# index를 abc순으로 - 그 다음은 한글 순으로 sort함 
nameDF.head()

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

In [50]:
nameDF.index.is_monotonic_increasing
# index가 실제로 단조증가 (오름차순) 으로 되어있는가 확인

True

In [62]:
nameDF.loc[ '삼성' : '삼성전자' ].head(2)
# 삼성부터 삼성전자 >> 해당하는 ticker의 row를 가져와서 DF로

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
삼성SDI,49548.613,-5.399,0.518,256.858,0.477,0.160,-9.674,765.051,156780.880,70399.125,149.010,0.727,1.619,114000.000,109000.000
삼성공조,923.961,3.377,9.094,84.026,4.617,3.382,4.248,1061.083,23804.424,11369.988,9.848,0.439,0.919,10450.000,11350.000

In [63]:
nameDF.loc['가' : '다'].tail(2)
# 가 ~ 다 까지의 순서의 row들을 DF로 출력함

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
농심,21816.236,5.422,5.382,1174.121,7.404,5.058,7.473,19290.592,282744.160,358663.800,22.783,1.554,1.225,439500.000,332500.000
농심홀딩스,4491.162,12.398,10.602,476.165,6.274,4.494,22.563,10263.555,167825.890,96838.414,15.005,0.918,1.590,154000.000,120500.000

#### 1.5.3.3 More about loc, iloc

In [46]:
nameDF.loc[["삼성전자"]]
nameDF[['순이익률(%)']].head()

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
삼성전자,2006534.900,13.164,9.499,190601.440,11.159,8.066,15.904,2197.652,23714.760,23587.871,11.467,1.063,1.069,25200.000,36040.000

         순이익률(%)
종목명
AK홀딩스     -1.334
BGF        3.526
BNK금융지주   10.253
BYC        7.222
CJ         2.604

In [47]:
# string, list
# ticker가 삼성전자인 것을 가져오는데, 거기서도 삼성전자의 순이익률 column만 보고 싶을 때
# '삼성전자' 가 index, '순이익률(%)' 이 column명
nameDF.loc['삼성전자', '순이익률(%)']
# 행렬 2차원 indexing 하듯이

9.499

In [66]:
# 만약 내가 2가지 row의 column 값을 보고 싶을 경우 
# 하나라도 string으로 전달하면 Series로 주네 
nameDF.loc[ ['삼성전자', '삼성SDI'], '순이익률(%)']

종목명
삼성전자    9.499
삼성SDI   0.518
Name: 순이익률(%), dtype: float64

In [67]:
# column도 2개를 가져 올 수 있음
nameDF.loc[ ['삼성전자', '삼성SDI'], ['순이익률(%)', 'EPS(원)']]

       순이익률(%)   EPS(원)
종목명
삼성전자     9.499 2197.652
삼성SDI    0.518  765.051

In [52]:
# range indexing
nameDF.loc['삼성': '삼성전자', :].head()
# 삼성이랑 삼성전자 까지의 row에서 모든 column을 가져올 것
# 이 : 를 잘 활용하자

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
삼성SDI,49548.613,-5.399,0.518,256.858,0.477,0.160,-9.674,765.051,156780.880,70399.125,149.010,0.727,1.619,114000.000,109000.000
삼성공조,923.961,3.377,9.094,84.026,4.617,3.382,4.248,1061.083,23804.424,11369.988,9.848,0.439,0.919,10450.000,11350.000
삼성물산,133446.750,0.278,20.125,26856.512,25.218,10.355,45.480,17856.860,98435.625,86752.920,7.840,1.422,1.614,140000.000,125500.000
삼성생명,277059.280,4.145,4.366,12095.730,5.276,0.544,nan,6056.165,128138.516,138529.640,18.163,0.858,0.794,110000.000,112500.000
삼성에스디에스,78534.586,7.490,5.982,4698.307,10.091,7.911,12.249,5673.722,59324.496,101494.984,44.768,4.282,2.503,254000.000,139500.000

In [69]:
nameDF.loc['삼성':'삼성전자', "순이익률(%)"]

종목명
삼성SDI       0.518
삼성공조        9.094
삼성물산       20.125
삼성생명        4.366
삼성에스디에스     5.982
삼성엔지니어링   -20.250
삼성전기        0.334
삼성전자        9.499
Name: 순이익률(%), dtype: float64

In [70]:
nameDF.loc['삼성':'삼성전자', ['순이익률(%)', "EPS(원)"]]

         순이익률(%)     EPS(원)
종목명
삼성SDI      0.518    765.051
삼성공조       9.094   1061.083
삼성물산      20.125  17856.860
삼성생명       4.366   6056.165
삼성에스디에스    5.982   5673.722
삼성엔지니어링  -20.250 -20337.280
삼성전기       0.334    144.180
삼성전자       9.499   2197.652

In [71]:
nameDF.iloc[ [ 0, 3], :]

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
종목명,,,,,,,,,,,,,,,
AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000

In [72]:
nameDF.iloc[ [ 0, 3], 0: 3]

        매출액(억원)  영업이익률(%)  순이익률(%)
종목명
AK홀딩스 28071.479     3.787   -1.334
BYC    1821.960    11.598    7.222

 - For Series data

In [53]:
a = pd.Series([1, 2, 3], index =['a', 'b', 'c'])
a

a    1
b    2
c    3
dtype: int64

In [74]:
a['a']

1

In [75]:
a.iloc[0]

1

In [76]:
a.loc['a']

1

In [77]:
a.iloc[2]
a.iloc[[2]]

3

c    3
dtype: int64

### 1.5.4 For Scalar Valye
 - scalar 값으로 subset 추출하기
 - use `.at` or `.iat`

In [78]:
df.head()
# index가 integer임

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
3,BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
4,CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

In [79]:
df.loc[100, '순이익률(%)'] 
# 여기서 100은 index넘버가 아니라 index의 이름 100(integer)임!! 지금 index가 0~ 숫자이므로

4.713

In [80]:
df.at[100, '순이익률(%)']
# loc과 비슷, 결과도 똑같음

4.713

In [81]:
# .at이나 .iat을 쓰는게 loc이나 iloc보다 훨씬 빠름
# Table이 크면 클수록 훨씬 빨라짐 
# jupyter에서는 timeit (time + iteration)을 통해서 코드의 실행속도를 알 수 있음

%timeit df.loc[100, '순이익률(%)']
%timeit df.at[100, '순이익률(%)']

19.5 µs ± 4.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
13 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [88]:
# Also works with Series

### 1.5.5 Boolean selection
 - Boolean Series로 subset 추출하는 방법

In [54]:
tmp_series = pd.Series({"a" : 1, "b": 2})
tmp_series

a    1
b    2
dtype: int64

In [55]:
tmp_series > 2
# 이딴 식으로 비교해도 Series안의 value값의 숫자에 맞춰서 broadcasting해줘서 tmp_series의 value들이 2보다 큰가 아닌가를 반환해줌
# boolean series로 반환해줌

a    False
b    False
dtype: bool

In [56]:
# 그 전에는 컬럼 이름이나 인덱스를 직접 명시해야했음
# 조건식을 만족하는 ROW나 column만 추출 하면 됨 >> boolean series로 들어가니까

In [57]:
tmp_df = pd.DataFrame( {"a" : [1, np.nan, 3, 4, np.nan], "b" : [5, 3, 3, 4, np.nan]} )

In [58]:
tmp_df

      a     b
0 1.000 5.000
1   nan 3.000
2 3.000 3.000
3 4.000 4.000
4   nan   nan

In [59]:
tmp_df3 = tmp_df > 2
tmp_df3
# 이렇게 DataFrame에서도 확장해서 이용할 수 있음
# nan값은 어떤 값과 비교하더라도 false값이 나옴

       a      b
0  False   True
1  False   True
2   True   True
3   True   True
4  False  False

#### 1.5.5.1 DataFrame 내에서 "Boolean Series" 만들기

In [94]:
df.head()

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
3,BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
4,CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

In [98]:
df['순이익률(%)'].head() 
df['영업이익률(%)'].head()

0   -1.334
1    3.526
2   10.253
3    7.222
4    2.604
Name: 순이익률(%), dtype: float64

0    3.787
1    4.236
2   13.455
3   11.598
4    5.789
Name: 영업이익률(%), dtype: float64

In [99]:
# 새로운 boolean series가 생김
# 해당 연도에 순이익률이 영업 이익률을 상회하는 종목들만 뽑아냄.
(df['순이익률(%)']> df['영업이익률(%)'] ).head()

In [61]:
a = (df['순이익률(%)'] > df['영업이익률(%)'])
a.sum()
# false는 0, true는 1에 상응하는 값임 >> a의 총합이 142면 순이익률이 영업이익률보다 
# 종목이 142개 있다는 이야기 
a.mean()
# 평균을 나타내면, 20%의 종목이 True임을 알 수 있음

142

0.20851688693098386

In [62]:
df['상회종목'] = (df['순이익률(%)'] > df['영업이익률(%)'])
df.tail()

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2,상회종목
676,휴비스,12050.846,2.788,1.753,211.199,5.437,2.405,4.184,607.136,11896.215,34929.990,12.798,0.653,0.222,7770.000,8210.000,False
677,휴스틸,4384.754,1.875,0.158,6.932,0.175,0.127,0.928,100.195,56901.895,63376.168,153.701,0.271,0.243,15400.000,15400.000,False
678,휴켐스,6004.260,7.261,5.700,342.227,7.760,4.709,9.516,896.118,12236.232,14688.032,17.074,1.250,1.042,15300.000,21700.000,False
679,흥국화재,42355.850,0.419,0.464,196.530,3.790,0.203,nan,301.592,6783.198,64998.605,13.926,0.619,0.065,4200.000,3705.000,True
680,흥아해운,8451.153,2.514,1.244,105.172,6.178,1.460,4.981,227.189,3784.747,18255.838,14.763,0.886,0.184,3315.000,2426.000,False

#### 1.5.5.2 Boolean series로 indexing하기

In [63]:
df.shape

(681, 17)

In [64]:
a.shape
# series지만 row개수는 똑같음

(681,)

In [65]:
df[a].head()
# 이렇게 하면, a 시리즈에서 true로 나온 녀석들만 subset으로 만들어 dataframe을 새로 만듦
df[a].shape

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2,상회종목
9,CS홀딩스,1389.707,16.333,21.302,296.039,10.913,10.858,12.273,18717.416,178497.380,120374.984,4.237,0.444,0.659,79300.000,80700.000,True
10,DB,2036.712,4.793,6.475,131.869,9.553,4.108,158.076,72.405,964.225,1118.296,6.843,0.514,0.443,495.000,734.000,True
13,DB하이텍,6665.950,18.747,19.012,1267.333,67.634,12.869,18.277,2847.226,5870.005,14975.904,5.022,2.436,0.955,14300.000,15900.000,True
33,KC코트렐,1867.743,-4.667,-3.614,-67.509,-11.419,-4.253,-16.087,-610.168,5120.945,17233.484,-10.770,1.283,0.381,6571.000,5960.000,True
41,KTB투자증권,2393.692,4.172,13.142,314.573,7.869,3.037,nan,443.977,6072.164,3390.651,5.102,0.373,0.668,2265.000,2925.000,True

(142, 17)

In [66]:
df.loc[a].shape
# 얘도 그냥 bracket이용하는 것과 똑같은 값을 리턴함

(142, 17)

#### 1.5.5.3 Multi boolean series

In [67]:
con1 = df["순이익률(%)"] > df['영업이익률(%)']
con2 = df['PBR(배)'] < 1

In [68]:
con1.head()
con2.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

0    False
1    False
2     True
3    False
4    False
Name: PBR(배), dtype: bool

In [69]:
# 위 두가지를 만족하는 조건을 찾고 싶다면? >> 둘을 만족하는 boolean series를 만들면 됨
# 우선 관계연산자를 알아야 함
# and 연산자 or 연산자를 c언어랑 비슷하게 씀
# and  >> &
# or >> |

In [70]:
final_con = (con1 & con2)
# 이러면 con1과 con2 모두 true인 것들만 true로 return하는 series를 반환함

In [71]:
final_con.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [72]:
df[final_con].head()
df[final_con].shape
# con1과 con2를 모두 만족하는 ticker에 해당하는 값들만 담아준다

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2,상회종목
9,CS홀딩스,1389.707,16.333,21.302,296.039,10.913,10.858,12.273,18717.416,178497.380,120374.984,4.237,0.444,0.659,79300.000,80700.000,True
10,DB,2036.712,4.793,6.475,131.869,9.553,4.108,158.076,72.405,964.225,1118.296,6.843,0.514,0.443,495.000,734.000,True
41,KTB투자증권,2393.692,4.172,13.142,314.573,7.869,3.037,nan,443.977,6072.164,3390.651,5.102,0.373,0.668,2265.000,2925.000,True
63,OCI,23015.205,-6.284,7.911,1820.685,3.494,2.474,-1.977,4205.815,123913.910,96502.360,17.832,0.605,0.777,75000.000,78700.000,True
69,SBS미디어홀딩스,4735.231,4.912,5.328,252.274,3.361,2.899,8.934,161.161,4857.421,3384.818,24.137,0.801,1.149,3890.000,2675.000,True

(83, 17)

### `isin()`

In [74]:
# 삼성전자랑, 삼성물산, 현대건설에 해당하는 데이너만 가져오고 싶을 떄
name_list = ['삼성전자', '삼성물산', '현대건설']

In [123]:
# 1. multiple boolean 을 이용하는 방법
cond1 = (df['종목명']== '삼성전자')
cond2 = (df['종목명'] == '현대건설')
cond3 = (df['종목명'] == '삼성물산')

finCond = (cond1 | cond2 | cond3)
df[finCond]

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2,상회종목
283,삼성물산,133446.750,0.278,20.125,26856.512,25.218,10.355,45.480,17856.860,98435.625,86752.920,7.840,1.422,1.614,140000.000,125500.000,True
288,삼성전자,2006534.900,13.164,9.499,190601.440,11.159,8.066,15.904,2197.652,23714.760,23587.871,11.467,1.063,1.069,25200.000,36040.000,False
641,현대건설,192331.800,5.664,3.451,6637.780,7.646,3.531,14.804,3777.241,51323.973,172565.120,7.558,0.556,0.165,28550.000,42800.000,False

In [125]:
# 2. index화 해서 loc으로 가져오는 방법
tempDF =  df.set_index('종목명')
tempDF.head()

In [130]:
tempDF.loc[name_list].head()
tempDF.loc[['삼성전자', '현대건설', '삼성물산']].head()

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2,상회종목
종목명,,,,,,,,,,,,,,,,
삼성전자,2006534.900,13.164,9.499,190601.440,11.159,8.066,15.904,2197.652,23714.760,23587.871,11.467,1.063,1.069,25200.000,36040.000,False
삼성물산,133446.750,0.278,20.125,26856.512,25.218,10.355,45.480,17856.860,98435.625,86752.920,7.840,1.422,1.614,140000.000,125500.000,True
현대건설,192331.800,5.664,3.451,6637.780,7.646,3.531,14.804,3777.241,51323.973,172565.120,7.558,0.556,0.165,28550.000,42800.000,False

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2,상회종목
종목명,,,,,,,,,,,,,,,,
삼성전자,2006534.900,13.164,9.499,190601.440,11.159,8.066,15.904,2197.652,23714.760,23587.871,11.467,1.063,1.069,25200.000,36040.000,False
현대건설,192331.800,5.664,3.451,6637.780,7.646,3.531,14.804,3777.241,51323.973,172565.120,7.558,0.556,0.165,28550.000,42800.000,False
삼성물산,133446.750,0.278,20.125,26856.512,25.218,10.355,45.480,17856.860,98435.625,86752.920,7.840,1.422,1.614,140000.000,125500.000,True

In [75]:
# 3. isin() 함수를 통해서 가져오는 방법 >> 역시  boolean series 방법
df['종목명'].isin(name_list)
# isin안에 list를 전달하면 여기 안에 있니 하고 series로 전달해줌( 있을 경우 true를 반환)

0      False
1      False
2      False
3      False
4      False
       ...
676    False
677    False
678    False
679    False
680    False
Name: 종목명, Length: 681, dtype: bool

In [133]:
df[ df['종목명'].isin(name_list)]

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2,상회종목
283,삼성물산,133446.750,0.278,20.125,26856.512,25.218,10.355,45.480,17856.860,98435.625,86752.920,7.840,1.422,1.614,140000.000,125500.000,True
288,삼성전자,2006534.900,13.164,9.499,190601.440,11.159,8.066,15.904,2197.652,23714.760,23587.871,11.467,1.063,1.069,25200.000,36040.000,False
641,현대건설,192331.800,5.664,3.451,6637.780,7.646,3.531,14.804,3777.241,51323.973,172565.120,7.558,0.556,0.165,28550.000,42800.000,False

### `all()` vs `any()`

In [135]:
a = (df['순이익률(%)'] > 0)

In [138]:
a.all()
# all >> boolean series에 대해서 전부다 true일 때 true를 반환
# all 했는데 false가 나오면 어느 하나라도 false인 값이 있다는 걸 뜻함

False

In [139]:
a.any()
# any >> 반대로 boolean series에서 하나라도 true면 true를 반환함

True

#### Example

In [76]:
a = pd.read_csv('./materials/my_data/symbol_sector.csv', index_col = 0)
a.head()

                 Sector
AJ네트웍스  산업용 기계 및 장비 임대업
AJ렌터카          운송장비 임대업
AK홀딩스            기타 금융업
AP우주통신         전자부품 제조업
BGF              종합 소매업

In [77]:
a['Sector'].value_counts()
# Series 안에 값들이 총 몇개씩 있는지 series type으로 반환해줌

기타 금융업              110
자동차 신품 부품 제조업        46
의약품 제조업              44
전자부품 제조업             38
1차 철강 제조업            38
                   ...
기타 상품 전문 소매업          1
동물성 및 식물성 유지 제조업      1
스포츠 서비스업              1
사진장비 및 광학기기 제조업       1
산업용 기계 및 장비 임대업       1
Name: Sector, Length: 129, dtype: int64

In [78]:
a['Sector'].value_counts().nlargest(5)
# 가장 많이 있는 sector가 위에서부터 5개 뭐인지 series 형태로 반환해줌

기타 금융업           110
자동차 신품 부품 제조업     46
의약품 제조업           44
전자부품 제조업          38
1차 철강 제조업         38
Name: Sector, dtype: int64

In [79]:
top5SectorList = a['Sector'].value_counts().nlargest(5).index
type(top5SectorList)

pandas.core.indexes.base.Index

In [81]:
a[ a['Sector'].isin(top5SectorList) ]
# 5대 섹터에 있는 기업들만 subset으로 반환할 수 있음

            Sector
AK홀딩스       기타 금융업
AP우주통신    전자부품 제조업
BNK금융지주     기타 금융업
CJ          기타 금융업
CS홀딩스       기타 금융업
...            ...
화인자산관리      기타 금융업
환인제약       의약품 제조업
휴리프       전자부품 제조업
휴스틸      1차 철강 제조업
흥양        전자부품 제조업

[276 rows x 1 columns]

# 2. 연산(Arithmetic)

In [82]:
import FinanceDataReader as fdr
price_df = fdr.DataReader("005930", '2009-09-16', '2018-03-21')

In [83]:
price_df.head()

             Open   High    Low  Close  Volume  Change
Date
2009-09-16  15400  16000  15320  15900  711387   0.034
2009-09-17  16120  16200  15920  16200  494941   0.019
2009-09-18  16200  16400  16080  16120  896503  -0.005
2009-09-21  16040  16200  15880  15960  337013  -0.010
2009-09-22  16000  16580  15959  16500  515790   0.034

## 2.1 연산기준
 - DataFrame은 기준이 columns
 - Series는 기준이 index
 - 따로 명시가 없다면 Series의 index가 DataFrame의 columns에 맞춰진다 (알아서 먼저 align함)

### 2.1.1 DataFrame & Series

In [165]:
# Subtract row Series
price_df.iloc[0]
(price_df - price_df.iloc[0]).head()
# 1번째 row의 값으로 나머지 row들을 빼주는 것 >> 일종의 normalizing이라고 생각하면 됨

Open      15400.000
High      16000.000
Low       15320.000
Close     15900.000
Volume   711387.000
Change        0.034
Name: 2009-09-16 00:00:00, dtype: float64

              Open    High     Low   Close      Volume  Change
Date
2009-09-16   0.000   0.000   0.000   0.000       0.000   0.000
2009-09-17 720.000 200.000 600.000 300.000 -216446.000  -0.015
2009-09-18 800.000 400.000 760.000 220.000  185116.000  -0.039
2009-09-21 640.000 200.000 560.000  60.000 -374374.000  -0.044
2009-09-22 600.000 580.000 639.000 600.000 -195597.000   0.000

In [166]:
# Subtract column Series
price_df['Open']

Date
2009-09-16    15400
2009-09-17    16120
2009-09-18    16200
2009-09-21    16040
2009-09-22    16000
              ...
2018-03-15    52000
2018-03-16    51220
2018-03-19    50620
2018-03-20    50700
2018-03-21    51780
Name: Open, Length: 2104, dtype: int64

In [84]:
(price_df - price_df['Open']).head()
# 연산시에 series의 index와 df의 column명을 align한 후 연산하는데, 지금 series의 index 
# 값들이 dataFRame의 column 에 없는 상태
# dataframe에 series의 index값에 해당하는 column들을 만든 후 연산을 해준 것
(price_df - price_df['Open']).shape

,2009-09-16 00:00:00,2009-09-17 00:00:00,2009-09-18 00:00:00,2009-09-21 00:00:00,2009-09-22 00:00:00,2009-09-23 00:00:00,2009-09-24 00:00:00,2009-09-25 00:00:00,2009-09-28 00:00:00,2009-09-29 00:00:00,2009-09-30 00:00:00,2009-10-01 00:00:00,2009-10-05 00:00:00,2009-10-06 00:00:00,2009-10-07 00:00:00,2009-10-08 00:00:00,2009-10-09 00:00:00,2009-10-12 00:00:00,2009-10-13 00:00:00,2009-10-14 00:00:00,2009-10-15 00:00:00,2009-10-16 00:00:00,2009-10-19 00:00:00,2009-10-20 00:00:00,2009-10-21 00:00:00,2009-10-22 00:00:00,2009-10-23 00:00:00,2009-10-26 00:00:00,2009-10-27 00:00:00,2009-10-28 00:00:00,2009-10-29 00:00:00,2009-10-30 00:00:00,2009-11-02 00:00:00,2009-11-03 00:00:00,2009-11-04 00:00:00,2009-11-05 00:00:00,2009-11-06 00:00:00,2009-11-09 00:00:00,2009-11-10 00:00:00,2009-11-11 00:00:00,2009-11-12 00:00:00,2009-11-13 00:00:00,2009-11-16 00:00:00,2009-11-17 00:00:00,2009-11-18 00:00:00,2009-11-19 00:00:00,2009-11-20 00:00:00,2009-11-23 00:00:00,2009-11-24 00:00:00,2009-11-25 00:00:00,2009-11-26 00:00:00,2009-11-27 00:00:00,2009-11-30 00:00:00,2009-12-01 00:00:00,2009-12-02 00:00:00,2009-12-03 00:00:00,2009-12-04 00:00:00,2009-12-07 00:00:00,2009-12-08 00:00:00,2009-12-09 00:00:00,2009-12-10 00:00:00,2009-12-11 00:00:00,2009-12-14 00:00:00,2009-12-15 00:00:00,2009-12-16 00:00:00,2009-12-17 00:00:00,2009-12-18 00:00:00,2009-12-21 00:00:00,2009-12-22 00:00:00,2009-12-23 00:00:00,2009-12-24 00:00:00,2009-12-28 00:00:00,2009-12-29 00:00:00,2009-12-30 00:00:00,2010-01-04 00:00:00,2010-01-05 00:00:00,2010-01-06 00:00:00,2010-01-07 00:00:00,2010-01-08 00:00:00,2010-01-11 00:00:00,2010-01-12 00:00:00,2010-01-13 00:00:00,2010-01-14 00:00:00,2010-01-15 00:00:00,2010-01-18 00:00:00,2010-01-19 00:00:00,2010-01-20 00:00:00,2010-01-21 00:00:00,2010-01-22 00:00:00,2010-01-25 00:00:00,2010-01-26 00:00:00,2010-01-27 00:00:00,2010-01-28 00:00:00,2010-01-29 00:00:00,2010-02-01 00:00:00,2010-02-02 00:00:00,2010-02-03 00:00:00,2010-02-04 00:00:00,2010-02-05 00:00:00,2010-02-08 00:00:00,2010-02-09 00:00:00,2010-02-10 00:00:00,2010-02-11 00:00:00,2010-02-12 00:00:00,2010-02-16 00:00:00,2010-02-17 00:00:00,2010-02-18 00:00:00,2010-02-19 00:00:00,2010-02-22 00:00:00,2010-02-23 00:00:00,2010-02-24 00:00:00,2010-02-25 00:00:00,2010-02-26 00:00:00,2010-03-02 00:00:00,2010-03-03 00:00:00,2010-03-04 00:00:00,2010-03-05 00:00:00,2010-03-08 00:00:00,2010-03-09 00:00:00,2010-03-10 00:00:00,2010-03-11 00:00:00,2010-03-12 00:00:00,2010-03-15 00:00:00,2010-03-16 00:00:00,2010-03-17 00:00:00,2010-03-18 00:00:00,2010-03-19 00:00:00,2010-03-22 00:00:00,2010-03-23 00:00:00,2010-03-24 00:00:00,2010-03-25 00:00:00,2010-03-26 00:00:00,2010-03-29 00:00:00,2010-03-30 00:00:00,2010-03-31 00:00:00,2010-04-01 00:00:00,2010-04-02 00:00:00,2010-04-05 00:00:00,2010-04-06 00:00:00,2010-04-07 00:00:00,2010-04-08 00:00:00,2010-04-09 00:00:00,2010-04-12 00:00:00,2010-04-13 00:00:00,2010-04-14 00:00:00,2010-04-15 00:00:00,2010-04-16 00:00:00,2010-04-19 00:00:00,2010-04-20 00:00:00,2010-04-21 00:00:00,2010-04-22 00:00:00,2010-04-23 00:00:00,2010-04-26 00:00:00,2010-04-27 00:00:00,2010-04-28 00:00:00,2010-04-29 00:00:00,2010-04-30 00:00:00,2010-05-03 00:00:00,2010-05-04 00:00:00,2010-05-06 00:00:00,2010-05-07 00:00:00,2010-05-10 00:00:00,2010-05-11 00:00:00,2010-05-12 00:00:00,2010-05-13 00:00:00,2010-05-14 00:00:00,2010-05-17 00:00:00,2010-05-18 00:00:00,2010-05-19 00:00:00,2010-05-20 00:00:00,2010-05-24 00:00:00,2010-05-25 00:00:00,2010-05-26 00:00:00,2010-05-27 00:00:00,2010-05-28 00:00:00,2010-05-31 00:00:00,2010-06-01 00:00:00,2010-06-03 00:00:00,2010-06-04 00:00:00,2010-06-07 00:00:00,2010-06-08 00:00:00,2010-06-09 00:00:00,2010-06-10 00:00:00,2010-06-11 00:00:00,2010-06-14 00:00:00,2010-06-15 00:00:00,2010-06-16 00:00:00,2010-06-17 00:00:00,2010-06-18 00:00:00,2010-06-21 00:00:00,2010-06-22 00:00:00,2010-06-23 00:00:00,2010-06-24 00:00:00,2010-06-25 00:00:00,2010-06-28 00:00:00,2010-06-29 00:00:00,2010-06-30 00:00:00,2010-07-01 00:00:00,2010-07-02 00:00:00,2010-07-05 00:00:00,2010-07-06 00:00:00,2010-07-07 00:00:00,2010-07-08 00:00:00,2010-07-09 00:00:00,2010-07-12 00:00:00,2010-07-13 00:00:00,2010-07-14 00:00:00,2010-07-15 00:00:00,2010-07-16 00:00:00,2010-07-19 00:00:00,2010-07-20 00:00:00,2010-07-21 00:00:00,2010-07-22 00:00:00,2010-07-23 00:00:00,2010-07-26 00:00:00,2010-07-27 00:00:00,2010-07-28 00:00:00,2010-07-29 00:00:00,2010-07-30 00:00:00,2010-08-02 00:00:00,2010-08-03 00:00:00,2010-08-04 00:00:00,2010-08-05 00:00:00,2010-08-06 00:00:00,2010-08-09 00:00:00,2010-08-10 00:00:00,2010-08-11 00:00:00,2010-08-12 00:00:00,2010-08-13 00:00:00,2010-08-16 00:00:00,2010-08-17 00:00:00,2010-08-18 00:00:00,2010-08-19 00:00:00,2010-08-20 00:00:00,2010-08-23 00:00:00,2010-08-24 00:00:00,2010-08-25 00:00:00,2010-08-26 00:00:00,2010-08-27 00:00:00,2010-08-30 00:00:00,2010-08-31 00:00:00,2010-09-01 00:00:00,2010-09-02 00:00:00,2010-09-03 00:00:00,2010-09-06 00:00:00,2010-09-07 00:00:00,2010-09-08 00:00:00,2010-09-09 00:00:00,2010-09-10 00:00:00,2010-09-13 00:00:00,2010-09-14 00:00:00,2010-09-15 00:00:00,2010-09-16 00:00:00,2010-09-17 00:00:00,2010-09-20 00:00:00,2010-09-24 00:00:00,2010-09-27 00:00:00,2010-09-28 00:00:00,2010-09-29 00:00:00,2010-09-30 00:00:00,2010-10-01 00:00:00,2010-10-04 00:00:00,2010-10-05 00:00:00,2010-10-06 00:00:00,2010-10-07 00:00:00,2010-10-08 00:00:00,2010-10-11 00:00:00,2010-10-12 00:00:00,2010-10-13 00:00:00,2010-10-14 00:00:00,2010-10-15 00:00:00,2010-10-18 00:00:00,2010-10-19 00:00:00,2010-10-20 00:00:00,2010-10-21 00:00:00,2010-10-22 00:00:00,2010-10-25 00:00:00,2010-10-26 00:00:00,2010-10-27 00:00:00,2010-10-28 00:00:00,2010-10-29 00:00:00,2010-11-01 00:00:00,2010-11-02 00:00:00,2010-11-03 00:00:00,2010-11-04 00:00:00,2010-11-05 00:00:00,2010-11-08 00:00:00,2010-11-09 00:00:00,2010-11-10 00:00:00,2010-11-11 00:00:00,2010-11-12 00:00:00,2010-11-15 00:00:00,2010-11-16 00:00:00,2010-11-17 00:00:00,2010-11-18 00:00:00,2010-11-19 00:00:00,2010-11-22 00:00:00,2010-11-23 00:00:00,2010-11-24 00:00:00,2010-11-25 00:00:00,2010-11-26 00:00:00,2010-11-29 00:00:00,2010-11-30 00:00:00,2010-12-01 00:00:00,2010-12-02 00:00:00,2010-12-03 00:00:00,2010-12-06 00:00:00,2010-12-07 00:00:00,2010-12-08 00:00:00,2010-12-09 00:00:00,2010-12-10 00:00:00,2010-12-13 00:00:00,2010-12-14 00:00:00,2010-12-15 00:00:00,2010-12-16 00:00:00,2010-12-17 00:00:00,2010-12-20 00:00:00,2010-12-21 00:00:00,2010-12-22 00:00:00,2010-12-23 00:00:00,2010-12-24 00:00:00,2010-12-27 00:00:00,2010-12-28 00:00:00,2010-12-29 00:00:00,2010-12-30 00:00:00,2011-01-03 00:00:00,2011-01-04 00:00:00,2011-01-05 00:00:00,2011-01-06 00:00:00,2011-01-07 00:00:00,2011-01-10 00:00:00,2011-01-11 00:00:00,2011-01-12 00:00:00,2011-01-13 00:00:00,2011-01-14 00:00:00,2011-01-17 00:00:00,2011-01-18 00:00:00,2011-01-19 00:00:00,2011-01-20 00:00:00,2011-01-21 00:00:00,2011-01-24 00:00:00,2011-01-25 00:00:00,2011-01-26 00:00:00,2011-01-27 00:00:00,2011-01-28 00:00:00,2011-01-31 00:00:00,2011-02-01 00:00:00,2011-02-07 00:00:00,2011-02-08 00:00:00,2011-02-09 00:00:00,2011-02-10 00:00:00,2011-02-11 00:00:00,2011-02-14 00:00:00,2011-02-15 00:00:00,2011-02-16 00:00:00,2011-02-17 00:00:00,2011-02-18 00:00:00,2011-02-21 00:00:00,2011-02-22 00:00:00,2011-02-23 00:00:00,2011-02-24 00:00:00,2011-02-25 00:00:00,2011-02-28 00:00:00,2011-03-02 00:00:00,2011-03-03 00:00:00,2011-03-04 00:00:00,2011-03-07 00:00:00,2011-03-08 00:00:00,2011-03-09 00:00:00,2011-03-10 00:00:00,2011-03-11 00:00:00,2011-03-14 00:00:00,2011-03-15 00:00:00,2011-03-16 00:00:00,2011-03-17 00:00:00,2011-03-18 00:00:00,2011-03-21 00:00:00,2011-03-22 00:00:00,2011-03-23 00:00:00,2011-03-24 00:00:00,2011-03-25 00:00:00,2011-03-28 00:00:00,2011-03-29 00:00:00,2011-03-30 00:00:00,2011-03-31 00:00:00,2011-04-01 00:00:00,2011-04-04 00:00:00,2011-04-05 00:00:00,2011-04-06 00:00:00,2011-04-07 00:00:00,2011-04-08 00:00:00,2011-04-11 00:00:00,2011-04-12 00:00:00,2011-04-13 00:00:00,2011-04-14 00:00:00,2011-04-15 00:00:00,2011-04-18 00:00:00,2011-04-19 00:00:00,2011-04-20 00:00:00,2011-04-21 00:00:00,2011-04-22 00:00:00,2011-04-25 00:00:00,2011-04-26 00:00:00,2011-04-27 00:00:00,2011-04-28 00:00:00,2011-04-29 00:00:00,2011-05-02 00:00:00,2011-05-03 00:00:00,2011-05-04 00:00:00,2011-05-06 00:00:00,2011-05-09 00:00:00,2011-05-11 00:00:00,2011-05-12 00:00:00,2011-05-13 00:00:00,2011-05-16 00:00:00,2011-05-17 00:00:00,2011-05-18 00:00:00,2011-05-19 00:00:00,2011-05-20 00:00:00,2011-05-23 00:00:00,2011-05-24 00:00:00,2011-05-25 00:00:00,2011-05-26 00:00:00,2011-05-27 00:00:00,2011-05-30 00:00:00,2011-05-31 00:00:00,2011-06-01 00:00:00,2011-06-02 00:00:00,2011-06-03 00:00:00,2011-06-07 00:00:00,2011-06-08 00:00:00,2011-06-09 00:00:00,2011-06-10 00:00:00,2011-06-13 00:00:00,2011-06-14 00:00:00,2011-06-15 00:00:00,2011-06-16 00:00:00,2011-06-17 00:00:00,2011-06-20 00:00:00,2011-06-21 00:00:00,2011-06-22 00:00:00,2011-06-23 00:00:00,2011-06-24 00:00:00,2011-06-27 00:00:00,2011-06-28 00:00:00,2011-06-29 00:00:00,2011-06-30 00:00:00,2011-07-01 00:00:00,2011-07-04 00:00:00,2011-07-05 00:00:00,2011-07-06 00:00:00,2011-07-07 00:00:00,2011-07-08 00:00:00,2011-07-11 00:00:00,2011-07-12 00:00:00,2011-07-13 00:00:00,2011-07-14 00:00:00,2011-07-15 00:00:00,2011-07-18 00:00:00,2011-07-19 00:00:00,2011-07-20 00:00:00,2011-07-21 00:00:00,2011-07-22 00:00:00,2011-07-25 00:00:00,2011-07-26 00:00:00,2011-07-27 00:00:00,2011-07-28 00:00:00,2011-07-29 00:00:00,2011-08-01 00:00:00,2011-08-02 00:00:00,2011-08-03 00:00:00,2011-08-04 00:00:00,2011-08-05 00:00:00,2011-08-08 00:00:00,2011-08-09 00:00:00,2011-08-10 00:00:00,2011-08-11 00:00:00,2011-08-12 00:00:00,2011-08-16 00:00:00,2011-08-17 00:00:00,2011-08-18 00:00:00,2011-08-19 00:00:00,2011-08-22 00:00:00,2011-08-23 00:00:00,2011-08-24 00:00:00,2011-08-25 00:00:00,2011-08-26 00:00:00,2011-08-29 00:00:00,2011-08-30 00:00:00,2011-08-31 00:00:00,2011-09-01 00:00:00,2011-09-02 00:00:00,2011-09-05 00:00:00,2011-09-06 00:00:00,2011-09-07 00:00:00,2011-09-08 00:00:00,2011-09-09 00:00:00,2011-09-14 00:00:00,2011-09-15 00:00:00,2011-09-16 00:00:00,2011-09-19 00:00:00,2011-09-20 00:00:00,2011-09-21 00:00:00,2011-09-22 00:00:00,2011-09-23 00:00:00,2011-09-26 00:00:00,2011-09-27 00:00:00,2011-09-28 00:00:00,2011-09-29 00:00:00,2011-09-30 00:00:00,2011-10-04 00:00:00,2011-10-05 00:00:00,2011-10-06 00:00:00,2011-10-07 00:00:00,2011-10-10 00:00:00,2011-10-11 00:00:00,2011-10-12 00:00:00,2011-10-13 00:00:00,2011-10-14 00:00:00,2011-10-17 00:00:00,2011-10-18 00:00:00,2011-10-19 00:00:00,2011-10-20 00:00:00,2011-10-21 00:00:00,2011-10-24 00:00:00,2011-10-25 00:00:00,2011-10-26 00:00:00,2011-10-27 00:00:00,2011-10-28 00:00:00,2011-10-31 00:00:00,2011-11-01 00:00:00,2011-11-02 00:00:00,2011-11-03 00:00:00,2011-11-04 00:00:00,2011-11-07 00:00:00,2011-11-08 00:00:00,2011-11-09 00:00:00,2011-11-10 00:00:00,2011-11-11 00:00:00,2011-11-14 00:00:00,2011-11-15 00:00:00,2011-11-16 00:00:00,2011-11-17 00:00:00,2011-11-18 00:00:00,2011-11-21 00:00:00,2011-11-22 00:00:00,2011-11-23 00:00:00,2011-11-24 00:00:00,2011-11-25 00:00:00,2011-11-28 00:00:00,2011-11-29 00:00:00,2011-11-30 00:00:00,2011-12-01 00:00:00,2011-12-02 00:00:00,2011-12-05 00:00:00,2011-12-06 00:00:00,2011-12-07 00:00:00,2011-12-08 00:00:00,2011-12-09 00:00:00,2011-12-12 00:00:00,2011-12-13 00:00:00,2011-12-14 00:00:00,2011-12-15 00:00:00,2011-12-16 00:00:00,2011-12-19 00:00:00,2011-12-20 00:00:00,2011-12-21 00:00:00,2011-12-22 00:00:00,2011-12-23 00:00:00,2011-12-26 00:00:00,2011-12-27 00:00:00,2011-12-28 00:00:00,2011-12-29 00:00:00,2012-01-02 00:00:00,2012-01-03 00:00:00,2012-01-04 00:00:00,2012-01-05 00:00:00,2012-01-06 00:00:00,2012-01-09 00:00:00,2012-01-10 00:00:00,2012-01-11 00:00:00,2012-01-12 00:00:00,2012-01-13 00:00:00,2012-01-16 00:00:00,2012-01-17 00:00:00,2012-01-18 00:00:00,2012-01-19 00:00:00,2012-01-20 00:00:00,2012-01-25 00:00:00,2012-01-26 00:00:00,2012-01-27 00:00:00,2012-01-30 00:00:00,2012-01-31 00:00:00,2012-02-01 00:00:00,2012-02-02 00:00:00,2012-02-03 00:00:00,2012-02-06 00:00:00,2012-02-07 00:00:00,2012-02-08 00:00:00,2012-02-09 00:00:00,2012-02-10 00:00:00,2012-02-13 00:00:00,2012-02-14 00:00:00,2012-02-15 00:00:00,2012-02-16 00:00:00,2012-02-17 00:00:00,2012-02-20 00:00:00,2012-02-21 00:00:00,2012-02-22 00:00:00,2012-02-23 00:00:00,2012-02-24 00:00:00,2012-02-27 00:00:00,2012-02-28 00:00:00,2012-02-29 00:00:00,2012-03-02 00:00:00,2012-03-05 00:00:00,2012-03-06 00:00:00,2012-03-07 00:00:00,2012-03-08 00:00:00,2012-03-09 00:00:00,2012-03-12 00:00:00,2012-03-13 00:00:00,2012-03-14 00:00:00,2012-03-15 00:00:00,2012-03-16 00:00:00,2012-03-19 00:00:00,2012-03-20 00:00:00,2012-03-21 00:00:00,2012-03-22 00:00:00,2012-03-23 00:00:00,2012-03-26 00:00:00,2012-03-27 00:00:00,2012-03-28 00:00:00,2012-03-29 00:00:00,2012-03-30 00:00:00,2012-04-02 00:00:00,2012-04-03 00:00:00,2012-04-04 00:00:00,2012-04-05 00:00:00,2012-04-06 00:00:00,2012-04-09 00:00:00,2012-04-10 00:00:00,2012-04-12 00:00:00,2012-04-13 00:00:00,2012-04-16 00:00:00,2012-04-17 00:00:00,2012-04-18 00:00:00,2012-04-19 00:00:00,2012-04-20 00:00:00,2012-04-23 00:00:00,2012-04-24 00:00:00,2012-04-25 00:00:00,2012-04-26 00:00:00,2012-04-27 00:00:00,2012-04-30 00:00:00,2012-05-02 00:00:00,2012-05-03 00:00:00,2012-05-04 00:00:00,2012-05-07 00:00:00,2012-05-08 00:00:00,2012-05-09 00:00:00,2012-05-10 00:00:00,2012-05-11 00:00:00,2012-05-14 00:00:00,2012-05-15 00:00:00,2012-05-16 00:00:00,2012-05-17 00:00:00,2012-05-18 00:00:00,2012-05-21 00:00:00,2012-05-22 00:00:00,2012-05-23 00:00:00,2012-05-24 00:00:00,2012-05-25 00:00:00,2012-05-29 00:00:00,2012-05-30 00:00:00,2012-05-31 00:00:00,2012-06-01 00:00:00,2012-06-04 00:00:00,2012-06-05 00:00:00,2012-06-07 00:00:00,2012-06-08 00:00:00,2012-06-11 00:00:00,2012-06-12 00:00:00,2012-06-13 00:00:00,2012-06-14 00:00:00,2012-06-15 00:00:00,2012-06-18 00:00:00,2012-06-19 00:00:00,2012-06-20 00:00:00,2012-06-21 00:00:00,2012-06-22 00:00:00,2012-06-25 00:00:00,2012-06-26 00:00:00,2012-06-27 00:00:00,2012-06-28 00:00:00,2012-06-29 00:00:00,2012-07-02 00:00:00,2012-07-03 00:00:00,2012-07-04 00:00:00,2012-07-05 00:00:00,2012-07-06 00:00:00,2012-07-09 00:00:00,2012-07-10 00:00:00,2012-07-11 00:00:00,2012-07-12 00:00:00,2012-07-13 00:00:00,2012-07-16 00:00:00,2012-07-17 00:00:00,2012-07-18 00:00:00,2012-07-19 00:00:00,2012-07-20 00:00:00,2012-07-23 00:00:00,2012-07-24 00:00:00,2012-07-25 00:00:00,2012-07-26 00:00:00,2012-07-27 00:00:00,2012-07-30 00:00:00,2012-07-31 00:00:00,2012-08-01 00:00:00,2012-08-02 00:00:00,2012-08-03 00:00:00,2012-08-06 00:00:00,2012-08-07 00:00:00,2012-08-08 00:00:00,2012-08-09 00:00:00,2012-08-10 00:00:00,2012-08-13 00:00:00,2012-08-14 00:00:00,2012-08-16 00:00:00,2012-08-17 00:00:00,2012-08-20 00:00:00,2012-08-21 00:00:00,2012-08-22 00:00:00,2012-08-23 00:00:00,2012-08-24 00:00:00,2012-08-27 00:00:00,2012-08-28 00:00:00,2012-08-29 00:00:00,2012-08-30 00:00:00,2012-08-31 00:00:00,2012-09-03 00:00:00,2012-09-04 00:00:00,2012-09-05 00:00:00,2012-09-06 00:00:00,2012-09-07 00:00:00,2012-09-10 00:00:00,2012-09-11 00:00:00,2012-09-12 00:00:00,2012-09-13 00:00:00,2012-09-14 00:00:00,2012-09-17 00:00:00,2012-09-18 00:00:00,2012-09-19 00:00:00,2012-09-20 00:00:00,2012-09-21 00:00:00,2012-09-24 00:00:00,2012-09-25 00:00:00,2012-09-26 00:00:00,2012-09-27 00:00:00,2012-09-28 00:00:00,2012-10-02 00:00:00,2012-10-04 00:00:00,2012-10-05 00:00:00,2012-10-08 00:00:00,2012-10-09 00:00:00,2012-10-10 00:00:00,2012-10-11 00:00:00,2012-10-12 00:00:00,2012-10-15 00:00:00,2012-10-16 00:00:00,2012-10-17 00:00:00,2012-10-18 00:00:00,2012-10-19 00:00:00,2012-10-22 00:00:00,2012-10-23 00:00:00,2012-10-24 00:00:00,2012-10-25 00:00:00,2012-10-26 00:00:00,2012-10-29 00:00:00,2012-10-30 00:00:00,2012-10-31 00:00:00,2012-11-01 00:00:00,2012-11-02 00:00:00,2012-11-05 00:00:00,2012-11-06 00:00:00,2012-11-07 00:00:00,2012-11-08 00:00:00,2012-11-09 00:00:00,2012-11-12 00:00:00,2012-11-13 00:00:00,2012-11-14 00:00:00,2012-11-15 00:00:00,2012-11-16 00:00:00,2012-11-19 00:00:00,2012-11-20 00:00:00,2012-11-21 00:00:00,2012-11-22 00:00:00,2012-11-23 00:00:00,2012-11-26 00:00:00,2012-11-27 00:00:00,2012-11-28 00:00:00,2012-11-29 00:00:00,2012-11-30 00:00:00,2012-12-03 00:00:00,2012-12-04 00:00:00,2012-12-05 00:00:00,2012-12-06 00:00:00,2012-12-07 00:00:00,2012-12-10 00:00:00,2012-12-11 00:00:00,2012-12-12 00:00:00,2012-12-13 00:00:00,2012-12-14 00:00:00,2012-12-17 00:00:00,2012-12-18 00:00:00,2012-12-20 00:00:00,2012-12-21 00:00:00,2012-12-24 00:00:00,2012-12-26 00:00:00,2012-12-27 00:00:00,2012-12-28 00:00:00,2013-01-02 00:00:00,2013-01-03 00:00:00,2013-01-04 00:00:00,2013-01-07 00:00:00,2013-01-08 00:00:00,2013-01-09 00:00:00,2013-01-10 00:00:00,2013-01-11 00:00:00,2013-01-14 00:00:00,2013-01-15 00:00:00,2013-01-16 00:00:00,2013-01-17 00:00:00,2013-01-18 00:00:00,2013-01-21 00:00:00,2013-01-22 00:00:00,2013-01-23 00:00:00,2013-01-24 00:00:00,2013-01-25 00:00:00,2013-01-28 00:00:00,2013-01-29 00:00:00,2013-01-30 00:00:00,2013-01-31 00:00:00,2013-02-01 00:00:00,2013-02-04 00:00:00,2013-02-05 00:00:00,2013-02-06 00:00:00,2013-02-07 00:00:00,2013-02-08 00:00:00,2013-02-12 00:00:00,2013-02-13 00:00:00,2013-02-14 00:00:00,2013-02-15 00:00:00,2013-02-18 00:00:00,2013-02-19 00:00:00,2013-02-20 00:00:00,2013-02-21 00:00:00,2013-02-22 00:00:00,2013-02-25 00:00:00,2013-02-26 00:00:00,2013-02-27 00:00:00,2013-02-28 00:00:00,2013-03-04 00:00:00,2013-03-05 00:00:00,2013-03-06 00:00:00,2013-03-07 00:00:00,2013-03-08 00:00:00,2013-03-11 00:00:00,2013-03-12 00:00:00,2013-03-13 00:00:00,2013-03-14 00:00:00,2013-03-15 00:00:00,2013-03-18 00:00:00,2013-03-19 00:00:00,2013-03-20 00:00:00,2013-03-21 00:00:00,2013-03-22 00:00:00,2013-03-25 00:00:00,2013-03-26 00:00:00,2013-03-27 00:00:00,2013-03-28 00:00:00,2013-03-29 00:00:00,2013-04-01 00:00:00,2013-04-02 00:00:00,2013-04-03 00:00:00,2013-04-04 00:00:00,2013-04-05 00:00:00,2013-04-08 00:00:00,2013-04-09 00:00:00,2013-04-10 00:00:00,2013-04-11 00:00:00,2013-04-12 00:00:00,2013-04-15 00:00:00,2013-04-16 00:00:00,2013-04-17 00:00:00,2013-04-18 00:00:00,2013-04-19 00:00:00,2013-04-22 00:00:00,2013-04-23 00:00:00,2013-04-24 00:00:00,2013-04-25 00:00:00,2013-04-26 00:00:00,2013-04-29 00:00:00,2013-04-30 00:00:00,2013-05-02 00:00:00,2013-05-03 00:00:00,2013-05-06 00:00:00,2013-05-07 00:00:00,2013-05-08 00:00:00,2013-05-09 00:00:00,2013-05-10 00:00:00,2013-05-13 00:00:00,2013-05-14 00:00:00,2013-05-15 00:00:00,2013-05-16 00:00:00,2013-05-20 00:00:00,2013-05-21 00:00:00,2013-05-22 00:00:00,2013-05-23 00:00:00,2013-05-24 00:00:00,2013-05-27 00:00:00,2013-05-28 00:00:00,2013-05-29 00:00:00,2013-05-30 00:00:00,2013-05-31 00:00:00,2013-06-03 00:00:00,2013-06-04 00:00:00,2013-06-05 00:00:00,2013-06-07 00:00:00,2013-06-10 00:00:00,2013-06-11 00:00:00,2013-06-12 00:00:00,2013-06-13 00:00:00,2013-06-14 00:00:00,2013-06-17 00:00:00,2013-06-18 00:00:00,2013-06-19 00:00:00,2013-06-20 00:00:00,2013-06-21 00:00:00,2013-06-24 00:00:00,2013-06-25 00:00:00,2013-06-26 00:00:00,2013-06-27 00:00:00,2013-06-28 00:00:00,2013-07-01 00:00:00,2013-07-02 00:00:00,2013-07-03 00:00:00,2013-07-04 00:00:00,2013-07-05 00:00:00,2013-07-08 00:00:00,2013-07-09 00:00:00,2013-07-10 00:00:00,2013-07-11 00:00:00,2013-07-12 00:00:00,2013-07-15 00:00:00,2013-07-16 00:00:00,2013-07-17 00:00:00,2013-07-18 00:00:00,2013-07-19 00:00:00,2013-07-22 00:00:00,2013-07-23 00:00:00,2013-07-24 00:00:00,2013-07-25 00:00:00,2013-07-26 00:00:00,2013-07-29 00:00:00,2013-07-30 00:00:00,2013-07-31 00:00:00,2013-08-01 00:00:00,2013-08-02 00:00:00,2013-08-05 00:00:00,2013-08-06 00:00:00,2013-08-07 00:00:00,2013-08-08 00:00:00,2013-08-09 00:00:00,2013-08-12 00:00:00,2013-08-13 00:00:00,2013-08-14 00:00:00,2013-08-16 00:00:00,2013-08-19 00:00:00,2013-08-20 00:00:00,2013-08-21 00:00:00,2013-08-22 00:00:00,2013-08-23 00:00:00,2013-08-26 00:00:00,2013-08-27 00:00:00,2013-08-28 00:00:00,2013-08-29 00:00:00,2013-08-30 00:00:00,2013-09-02 00:00:00,2013-09-03 00:00:00,2013-09-04 00:00:00,2013-09-05 00:00:00,2013-09-06 00:00:00,2013-09-09 00:00:00,2013-09-10 00:00:00,2013-09-11 00:00:00,2013-09-12 00:00:00,2013-09-13 00:00:00,2013-09-16 00:00:00,2013-09-17 00:00:00

(2104, 2110)

In [85]:
# 그러면 series의 index와 dataframe의 index를  align해서 연산을 하는 방법은?

### DataFrame & DataFrame의 연산
 - index, column이 일치하는 것 끼리만 element-wise 연산이 이루어지고 나머지는 nan 처리

In [170]:
price_df[ ['Open', 'Low'] ].iloc[:2]

             Open    Low
Date
2009-09-16  15400  15320
2009-09-17  16120  15920

In [172]:
price_df - price_df[ ['Open', 'Low']].iloc[:2]
# 포개어지는 2*2 행렬 빼고는 모두 쓰레기값들이 연산이 된다 >> 모조리 nan 값

            Change  Close  High   Low  Open  Volume
Date
2009-09-16     nan    nan   nan 0.000 0.000     nan
2009-09-17     nan    nan   nan 0.000 0.000     nan
2009-09-18     nan    nan   nan   nan   nan     nan
2009-09-21     nan    nan   nan   nan   nan     nan
2009-09-22     nan    nan   nan   nan   nan     nan
...            ...    ...   ...   ...   ...     ...
2018-03-15     nan    nan   nan   nan   nan     nan
2018-03-16     nan    nan   nan   nan   nan     nan
2018-03-19     nan    nan   nan   nan   nan     nan
2018-03-20     nan    nan   nan   nan   nan     nan
2018-03-21     nan    nan   nan   nan   nan     nan

[2104 rows x 6 columns]

### 연산 관련 built-in 함수 사용
 - axis란?
 - 연산은 기본적으로 "axis를 변형 (줄이거나 늘리는)하는 방식"
  ==> 딱히 명시되어있지 않다면, default 로

In [86]:
df = pd.read_csv("./materials/my_data/naver_finance/2015_12.csv")

In [87]:
# numpy로 맛보기 
a = np.array( [1, 2, 3])
b = np.array( [1, 2, 3])
a
b

array([1, 2, 3])

array([1, 2, 3])

In [88]:
np.sum( [a, b])
np.sum( [a, b], axis = None)
# num에서 axis 안 썼을 떄의 default는 None이며, 주어진 array안의 모든 값을 더해서 return

12

12

In [89]:
np.sum( [a, b], axis = 0)
# numpy array 2개를 list에 담아서 sum함 >> 2차원 numpy array로 생각해도 됨
# 그걸 연산해서 numpy array로 return해줌
# axis = 0의 경우 2차원 배열의 세로 방향으로 sum을 해줌

array([2, 4, 6])

In [90]:
np.sum( [a, b], axis = 1)
# axis = 1의 경우 2차원 배열의 가로 방향으로 sum을 해줌

array([6, 6])

In [18]:
[    0  1  2
   0 [1, 2, 3],
   1 [1, 2, 3]
]
# >> 2 * 3 행렬로 볼 수 있음.
# 여기에서 axis 0은 y축을 의미하고, axis 1은 x축을 의미함

In [ ]:
 axis = 0 >>            0                      1
 axis = 1 >>     0      1      2         0      1      2
 axis = 2 >>    0 1    0 1    0 1       0 1    0 1    0 1
           [  [[1,2], [2,4], [3,6]],  [[1,2], [2,4], [3,6]]  ]

# 가장 원시적인, 바깥의 index부터 오름차순으로 axis 0 ~ 이 된다..

In [91]:
# sum은 결국 인자들을 합치겠다는 것 >> axis를 줄이는 방식이다
# axis = 0 >> 가장 원시적인 index를 없애고 싶다는 것 >> 이 데이터들을 구분하지 않고
# 하나로 합치고싶다
kk = np.array([  [[1,2], [2,4], [3,6]],  [[1,2], [2,4], [3,6]]  ])
np.sum( kk, axis = 0)
np.sum( kk, axis = 1)
np.sum( kk, axis = 2)

array([[ 2,  4],
       [ 4,  8],
       [ 6, 12]])

array([[ 6, 12],
       [ 6, 12]])

array([[3, 6, 9],
       [3, 6, 9]])

 - Note: shift + tab을 이용해서 주석 설명을 보는 것이 가장 정확함.

In [26]:
df.head()

,ticker,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000
3,BYC,1821.960,11.598,7.222,131.581,3.546,2.024,13.235,15693.808,453030.620,216899.980,29.279,1.014,2.118,459500.000,397000.000
4,CJ,211667.080,5.789,2.604,5511.155,5.874,2.365,5.821,5780.626,110304.560,594563.900,40.944,2.146,0.398,236684.000,176334.000

In [27]:
df[ ['순이익률(%)', 'PER(배)']].head()
# 2차원 배열과 같은 형태

   순이익률(%)  PER(배)
0   -1.334 -19.472
1    3.526  28.779
2   10.253   4.544
3    7.222  29.279
4    2.604  40.944

In [37]:
df[ ['순이익률(%)', 'PER(배)']].sum()  
# default >> axis = 0 (= None) >> numpy랑은 다름
# 가장 원시적인 index가 뭐냐? 순이익률, PER 의 두 index 
# 얘네를 기준으로 싹다 sum해준다

순이익률(%)    5214.630
PER(배)    12639.536
dtype: float64

In [38]:
df[ ['순이익률(%)', 'PER(배)']].sum(axis = 1)
# 그다음 원시적인 index는? 순이익률과 PER를 구성하는 list들의 index
# 얘네를 기준으로 싹다 sum 해준다

0     -20.806
1      32.305
2      14.797
3      36.501
4      43.548
        ...
676    14.551
677   153.859
678    22.774
679    14.390
680    16.007
Length: 681, dtype: float64

In [39]:
df[ ['순이익률(%)', 'PER(배)']].mean()

순이익률(%)    7.669
PER(배)    18.921
dtype: float64

In [92]:
# DataFrame - Series
# df's columns : o, h, l, c
# series' index : o, h, l, c
price_df = fdr.DataReader("005930", '2009-09-16', '2018-03-21')

In [93]:
price_df.mean()
# default -> axis = None 
# 가장 원시적인 index는? open, high, low, close, volume, change
# 이것들을 기준으로 mean을 구해준다.

Open      26950.998
High      27214.787
Low       26677.235
Close     26947.405
Volume   291897.414
Change        0.001
dtype: float64

In [94]:
(price_df - price_df.mean()).head()
# price_df.mean()의 series에 index가 다 있으므로 이거에 맞춰서 align함 
# 사칙연산은 broadcasting

                 Open       High        Low      Close     Volume  Change
Date
2009-09-16 -11550.998 -11214.787 -11357.235 -11047.405 419489.586   0.033
2009-09-17 -10830.998 -11014.787 -10757.235 -10747.405 203043.586   0.018
2009-09-18 -10750.998 -10814.787 -10597.235 -10827.405 604605.586  -0.006
2009-09-21 -10910.998 -11014.787 -10797.235 -10987.405  45115.586  -0.011
2009-09-22 -10950.998 -10634.787 -10718.235 -10447.405 223892.586   0.033

 - 아래 구문은 연산이 불가능 했었음

In [15]:
close_series = price_df['Close']
close_series
# index가 date임 
# 반면 기존의 dataframe은 index가 column명, 즉 open, close etc이므로 align이 안된다

Date
2009-09-16    15900
2009-09-17    16200
2009-09-18    16120
2009-09-21    15960
2009-09-22    16500
              ...
2018-03-15    51540
2018-03-16    51140
2018-03-19    50740
2018-03-20    51200
2018-03-21    51060
Name: Close, Length: 2104, dtype: int64

 - -> 하지만 DataFrame이 제공하는 연산관련 함수를 이용하면 가능!

In [18]:
(price_df - close_series).head()
# 이렇게 하면 안됨

In [17]:
# 이렇게 하면 된다.
price_df.sub(close_series, axis = 0).head()
# 빼는데, axis는 0을 기준으로

 - `sub()`의 경우 description에 'For Series input, axis to match Series index on'이라고 써있음
     - axis = 0 or 1은 무조건 description 보고 판단한 후에 'axis 는 해당 axis를 변형( 늘이거나 줄이는 것) 적용하기

### Example
 - Momentum 판단하기 -> 추세가 있나 없나 판단하는 지표

In [26]:
b = pd.read_csv('./materials/my_data/multi_price.csv', index_col = 0)

In [27]:
b.head()

,AJ네트웍스,AJ렌터카,AK홀딩스,BGF,BNK금융지주,BYC,CJ,CJ CGV,CJ대한통운,CJ씨푸드,CJ제일제당,CJ헬로,CS홀딩스,DB,DB금융투자,DB손해보험,DB하이텍,DGB금융지주,DRB동일,DSR
date_time,,,,,,,,,,,,,,,,,,,,
2017-01-02,6500.000,8330.000,53100.000,41780.000,8670.000,398000.000,188000.000,69000.000,179500.000,3665.000,359000.000,9370.000,80500.000,743.000,3285.000,61800.000,16300.000,9650.000,11899.000,9350.000
2017-01-03,6500.000,8320.000,52100.000,42811.000,8590.000,399000.000,185500.000,68000.000,176500.000,3700.000,351500.000,9290.000,78800.000,742.000,3315.000,60900.000,17250.000,9600.000,11704.000,9200.000
2017-01-04,6500.000,8310.000,51100.000,42089.000,8670.000,396000.000,185000.000,71000.000,175500.000,3605.000,350500.000,9280.000,78700.000,790.000,3405.000,62600.000,17700.000,9760.000,12143.000,9080.000
2017-01-05,6500.000,8490.000,51900.000,43171.000,8700.000,397000.000,191000.000,74400.000,175500.000,3625.000,360000.000,9130.000,77900.000,802.000,3455.000,62800.000,17950.000,9740.000,12386.000,9030.000
2017-01-06,6500.000,8400.000,52100.000,43532.000,8700.000,395000.000,192500.000,74600.000,177500.000,3605.000,361000.000,9110.000,77600.000,800.000,3475.000,63000.000,18450.000,9820.000,12338.000,8730.000

In [28]:
momentumSeries = b.loc['2018-08-09'] / b.loc['2017-08-09'] - 1
# Series와 Series의 나눗셈 - 1 
# 1년전 대비 종가가 얼마나 추세가 있냐 보는 것.

In [29]:
momentumSeries.head()

AJ네트웍스    -0.256
AJ렌터카      0.057
AK홀딩스      0.020
BGF       -0.785
BNK금융지주   -0.212
dtype: float64

In [32]:
momentumSeries.nlargest(3)
# 1년 Momentum 지표가 가장 큰 3개. 
# 이 3개는 약 10% 정도 상승했음 종가가

DB       0.142
DB금융투자   0.118
CJ헬로     0.088
dtype: float64

### Dealing with NaN value

In [35]:
None == None
# 아무것도 없다, 데이터가 존재하지 않는다는 뜻 >> python에서 기본적으로 제공함

True

In [36]:
np.nan == np.nan
# pandas에서 제공하는 numpy의 nan >> False가 나온다 
# Why?

False

In [38]:
5 < np.nan
5 > np.nan
5 == np.nan
# 어느 상황에서도 False를 보이고 있음. >> 어차피 nan은 쓰레기 값이므로 비교연산이 가능하지 않음.

False

False

False

 - 아래 operation만 True를 return함

In [40]:
np.nan != 5

True

In [42]:
df1 = pd.DataFrame( { 'a' : [1, 2, 3], 'b' : [np.nan, 4, np.nan]})
df1

   a     b
0  1   nan
1  2 4.000
2  3   nan

### nan이 있을 때의 boolean Series

In [47]:
df1['b'] == df1['b']
# np.nan == np.nan >> false가 나오므로

0    False
1     True
2    False
Name: b, dtype: bool

In [49]:
df1.ge(2)
df1.le(2)
# ge = Greater or Equal than X 
# le = Less of Equal than X
# >> 둘다 모두 DataFrame의 built-in 함수

       a      b
0  False  False
1   True   True
2   True  False

       a      b
0   True  False
1   True  False
2  False  False

 - 따라서 아래와 같은 구문은 위험할 수 있음 (nan값을 하지 않고 비교연산으로 boolean series를 return하는 것)

In [51]:
df.head(3)

,ticker,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.479,3.787,-1.334,-374.431,-7.677,-1.421,15.120,-3245.741,43497.723,211899.220,-19.472,1.453,0.298,63200.000,56000.000
1,BGF,43342.800,4.236,3.526,1528.413,22.771,10.327,271.957,3071.872,15605.457,87779.875,28.779,5.665,1.007,44202.000,42140.000
2,BNK금융지주,51740.254,13.455,10.253,5304.712,9.116,0.609,nan,1853.180,21665.062,19749.037,4.544,0.389,0.426,8420.000,8680.000

In [52]:
df.shape
df['PER(배)'].count()
# 3가지 종목은 비어있음을 알 수 있음. 
# 이게 원래 data가 있는거닞

(681, 16)

668

In [53]:
df['PER(배)'] > 1
# 3개의 nan 값에 있어서는 어떤 비교연산을 하던 false를 뱉을 것.

0      False
1       True
2       True
3       True
4       True
       ...
676     True
677     True
678     True
679     True
680     True
Name: PER(배), Length: 681, dtype: bool

#### Series data에서 nan의 유무를 알아보는 방법

In [55]:
df['순이익률(%)'].hasnans
# 몇개인지는 알려주지 않고 해당 series에 nan 값이 있니없니만 알려줌

True

In [59]:
# Generate Boolean Series
# isna, isnull 둘다 아무거나 써도 됨
df['순이익률(%)'].isna().any()
  # >> nan값이 하나라도 있니? True
df['순이익률(%)'].isna().sum()
  # >> nan 값이 총 몇개니? (true = 1이므로) >> 1개

True

1

### DataFrame에서 nan의 유무를 알아보는 방법

In [61]:
df.isna().head()

,ticker,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [62]:
df.isnull().any(axis = 0) 
# 각 column별로 nan값이 하나라도 있는지 알려줌

ticker       False
매출액(억원)       True
영업이익률(%)      True
순이익률(%)       True
당기순이익(억원)     True
ROE(%)        True
ROA(%)        True
ROIC(%)       True
EPS(원)       False
BPS(원)       False
SPS(원)       False
PER(배)        True
PBR(배)       False
PSR(배)        True
price        False
price2       False
dtype: bool

In [65]:
df.set_index('ticker').isna().any(axis = 1)
# 각 ticker별로 nan 값이 하나라도 있는지 알려줌

ticker
AK홀딩스      False
BGF        False
BNK금융지주     True
BYC        False
CJ         False
           ...
휴비스        False
휴스틸        False
휴켐스        False
흥국화재        True
흥아해운       False
Length: 681, dtype: bool

In [68]:
df.isna().any().any()
# any를 하면 이미 series로 반환하는데, 거기에 또 any를 씌우므로 이 DF에 nan값이 하나라도 있는지 검증하는 것이 됨

True

In [70]:
df.isna().any().all()
# 모든 column에 nan이 하나씩이라도 있니?
# 그러나 모든 column에 nan이 하나씩 있지는 않았음

False

 - 참고: 두 개의 DataFrame이 완전히 같은지 판단하려면, equals를 사용

In [71]:
df1['b'] == df1['b']

0    False
1     True
2    False
Name: b, dtype: bool

In [74]:
df1['b'].equals(df1['b'])
# nan이 존재하더라도 감안해서 비교연산을 해준다.

True

#### 둘 다 nan이 아닌 값만 추출하고 싶을 때.

In [76]:
# example
df3 = pd.DataFrame({'a' : [1, np.nan, 3], 'b': [np.nan, 2, 3]})
df3

      a     b
0 1.000   nan
1   nan 2.000
2 3.000 3.000

In [81]:
# 여기서 row 기준으로 하나라도 nan value를 가지고 있을 떄 날려버리고 싶을 경우 

# 1. boolean selection을 활용
df3.notnull()
df3.notnull()
# isna 와 반대의 결과를 돌려준다

       a      b
0   True  False
1  False   True
2   True   True

       a      b
0   True  False
1  False   True
2   True   True

In [82]:
df3[df3['a'].notnull() & df3['b'].notnull()]

      a     b
2 3.000 3.000

In [83]:
# 2. DataFRame자체에 isnull을 하는 방법
df3.notnull().all(axis = 1)
# axis 1 (수평 방향으로) 전부다 true냐 를 반환해줌

0    False
1    False
2     True
dtype: bool

In [85]:
# 3. dropna 함수
# column의 특정 row에 nan값이 하나라도 있으면 쳐내는 것
df3.dropna()

      a     b
2 3.000 3.000

In [87]:
# 근데 데이터가 무지 많은데 데이터가 하나가 nan이라고 다 쳐내기는 아깝다
# subset에 있는 컬럼 중에 하나라도 (혹은 전부, arg로 선택 가능) null이면 drop한다
df3.dropna(subset = ['a'])
# a라는 컬럼에 nan이 있으면 그 row를 지워내라

      a     b
0 1.000   nan
2 3.000 3.000